# Generated by Django 2.0.6 on 2018-06-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('duracao', models.SmallIntegerField()),
                ('descricao', models.TextField()),
            ],
        ),
    ]
